name: 'Goldfish&Iron'
favicon: null
layout_spectrum: 0.6464946903288364
typography_spectrum: 0.21974823554046452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12290698406286538
  lightness: 0.8444583269301802
  saturation: 0.5016361668240279
  rhythmicContrast: 0.6697364347055554
purpose: []
